name: Check Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: lfgw
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
           packages: >
             latex latex-bin scheme-basic koma-script luatexbase luatex
      - run: lualatex main
