name: Check Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
           package_file: tl_packages
      - run: lualatex main
      - name: Prepare build dir
        run: |
          mkdir build
          cp main.pdf build/
      - name: Upload build artifats
        uses: actions/upload-artifact@v4
        with:
          path: build
      - name: Upload to gh-pages branch
        if: >
          (github.repository == 'demo-kopp/dante-2024') &&
          (github.ref == 'refs/heads/main')
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: build
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
