name: Check Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: lualatex main
      - run: texlogsieve --no-heartbeat main.log
      - name: Prepare build dir
        run: |
          mkdir build
          cp main.pdf build/
      - name: Upload build artifats
        uses: actions/upload-artifact@v4
        with:
          path: build
