name: Check Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
           packages: >
             latex latex-bin scheme-basic koma-script luatexbase luatex
      - run: lualatex main
      - name: Upload build artifats
        uses: actions/upload-artifact@v4
        with:
          path: main.pdf
